import math

# Game Settings
RES = (WIDTH, HEIGHT) = (1920, 1080)
HALF_WIDTH = WIDTH//2
HALF_HEIGHT = HEIGHT//2
FPS = 144
CHUNK_SIZE = WIDTH/16

# Player Settings
PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002
PLAYER_SIZE_SCALE = 60

# Mouse Settings
MOUSE_SENSITIVITY = 0.0002
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 400
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

# Map Colors
FLOOR_COLOR = (65, 46, 65)

# RayCasting Settings
SET_FOV = 90
SET_GAMMA = 1
GAMMA = SET_GAMMA/50000
FOV = math.pi/(180/SET_FOV)
HALF_FOV = FOV/2
NUM_RAYS = WIDTH//2
HALF_NUM_RAYS = NUM_RAYS/2
DELTA_ANGLE = FOV/NUM_RAYS
MAX_DEPTH = 20
SCREEN_DIST = HALF_WIDTH/math.tan(HALF_FOV)
SCALE = WIDTH//NUM_RAYS

# Textures
TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE//2